language: python
python:
    - "2.6"
    - "2.7"
before_install:
    - sudo add-apt-repository -y ppa:kivy-team/kivy
    - sudo apt-get install python-kivy
    - sudo apt-get install kivy-example
install:
    - pip install pip
    - pip install setuptools
    - pip install wsgiref
    - pip install -r requirements.txt
script: nosetests
